### ISSUE TITLE
run COMPARE_BELTS_RESPONSES and AXES_MAP_CALIBRATION get error

### ISSUE THREAD

**Issue by silentycj** [Frix-x/klippain-shaketune#98] opened 2024-05-01 07:45 UTC
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

 v3.0.0-1-g56a5502

### Describe the bug and expected behavior

run COMPARE_BELTS_RESPONSES and AXES_MAP_CALIBRATION get error

### Additional information and klippy.log

Traceback (most recent call last):

  File "/home/orangepi/klippain_shaketune/src/is_workflow.py", line 408, in main
    graph_creator.create_graph()
  File "/home/orangepi/klippain_shaketune/src/is_workflow.py", line 218, in create_graph
    fig = belts_calibration(
          ^^^^^^^^^^^^^^^^^^
  File "/home/orangepi/klippain_shaketune/src/graph_creators/graph_belts.py", line 461, in belts_calibration
    datas = [parse_log(fn) for fn in lognames]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/orangepi/klippain_shaketune/src/graph_creators/graph_belts.py", line 461, in <listcomp>
    datas = [parse_log(fn) for fn in lognames]
             ^^^^^^^^^^^^^
  File "/home/orangepi/klippain_shaketune/src/helpers/common_func.py", line 24, in parse_log
    return np.loadtxt(logname, comments='#', delimiter=',')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orangepi/klippain_shaketune-env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1373, in loadtxt
    arr = _read(fname, dtype=dtype, comment=comment, delimiter=delimiter,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/orangepi/klippain_shaketune-env/lib/python3.11/site-packages/numpy/lib/npyio.py", line 1016, in _read
    arr = _load_from_filelike(
          ^^^^^^^^^^^^^^^^^^^^
ValueError: the number of columns changed from 4 to 1 at row 397302; use `usecols` to select a subset and avoid this error
Shake&Tune version: v3.0.0-1-g56a5502
Error while generating the graphs: the number of columns changed from 4 to 1 at row 397302; use `usecols` to select a subset and avoid this error

Stats 4705.0: gcodein=0  mcu: mcu_awake=0.015 mcu_task_avg=0.000018 mcu_task_stddev=0.000016 bytes_write=3175634 bytes_read=435143 bytes_retransmit=0 bytes_invalid=0 send_seq=54824 receive_seq=54824 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=47999154 btt_adxl345: mcu_awake=0.000 mcu_task_avg=0.000003 mcu_task_stddev=0.000003 bytes_write=22211 bytes_read=4941765 bytes_retransmit=9 bytes_invalid=0 send_seq=3227 receive_seq=3227 retransmit_seq=2 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=12000186 adj=12000592 sht36v2: mcu_awake=0.003 mcu_task_avg=0.000018 mcu_task_stddev=0.000019 bytes_write=28102 bytes_read=5187933 bytes_retransmit=0 bytes_invalid=0 send_seq=3720 receive_seq=3720 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=47999490 adj=48000708  MCU: temp=47.0 CAN: temp=32.0 SHT36-V2: temp=40.4 ElectronicsBox: temp=44.0 heater_bed: target=0 temp=26.3 pwm=0.000 sysload=1.82 cputime=145.080 memavail=584980 print_time=2245.003 buffer_time=0.000 print_stall=0 extruder: target=0 temp=25.3 pwm=0.000
Command {shaketune} finished

==================================================================================
Traceback (most recent call last):

  File "/home/orangepi/klippain_shaketune/src/is_workflow.py", line 408, in main
    graph_creator.create_graph()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AxesMapFinder' object has no attribute 'create_graph'
Shake&Tune version: v3.0.0-1-g56a5502
Error while generating the graphs: 'AxesMapFinder' object has no attribute 'create_graph'

Stats 4326.5: gcodein=0  mcu: mcu_awake=0.121 mcu_task_avg=0.000014 mcu_task_stddev=0.000007 bytes_write=34851 bytes_read=69076 bytes_retransmit=0 bytes_invalid=0 send_seq=2158 receive_seq=2158 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=47999304 btt_adxl345: mcu_awake=0.000 mcu_task_avg=0.000003 mcu_task_stddev=0.000003 bytes_write=1816 bytes_read=7331 bytes_retransmit=9 bytes_invalid=0 send_seq=273 receive_seq=273 retransmit_seq=2 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=12000187 adj=12000362 sht36v2: mcu_awake=0.503 mcu_task_avg=0.000041 mcu_task_stddev=0.000026 bytes_write=7692 bytes_read=193012 bytes_retransmit=0 bytes_invalid=0 send_seq=764 receive_seq=764 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=47999528 adj=48000223  MCU: temp=49.3 CAN: temp=31.7 SHT36-V2: temp=40.0 ElectronicsBox: temp=48.1 heater_bed: target=0 temp=26.1 pwm=0.000 sysload=1.32 cputime=20.307 memavail=616468 print_time=1874.255 buffer_time=0.000 print_stall=0 extruder: target=0 temp=25.2 pwm=0.000
Command {shaketune} finished

**Comment by Frix-x** [comment] 2024-05-12 16:29
This is a mostly duplicate of #99. axes_map detection is currently not working and leave CSV files in place in the /tmp folder. So they are catched and make the following vibrations measurement macro call to crash.

Just reboot the pi to cleanup the /tmp folder and don't run the AXES_MAP_CALIBRATION for now, the rest should be ok.

I'm closing this in favor of #99 to track and fix the issue.

**Closed by Frix-x** 2024-05-12 16:29 UTC
Labels: bug
