### ISSUE TITLE
BTT EBB SB2209 USB with lis2dw is not working

### ISSUE THREAD

**Issue by calderon67** [Frix-x/klippain-shaketune#176] opened 2024-12-16 21:50 UTC
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.1.0-1-g66f5e32e

### Describe the bug and expected behavior

I am trying to run the testing commands with my sb2209 usb version, which has a lis2dw instead of the adxl345. The query and the test run perfectly well in the native version of klipper, but none of the shake and tune commands run. They just perform an emergency stop after being called.

### Additional information and klippy.log

[klippy (23).log](https://github.com/user-attachments/files/18157428/klippy.23.log)

**Comment by Frix-x** [comment] 2024-12-16 22:55
Hello,
This is a duplicate of #172 due to a change in the latest Klipper version. Please downgrade Klipper for now if you want to continue using Shake&Tune until I release a fix (I was on holiday until today, so the fix should come pretty soon).

**Closed by Frix-x** 2024-12-16 22:55 UTC
Labels: bug
