### ISSUE TITLE
Shaketune vibration not compiling CSV data into graphs.

### ISSUE THREAD

**Issue by cromine11** [Frix-x/klippain-shaketune#79] opened 2024-03-17 13:57 UTC
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.6.1-0-g82b91c1b

### Describe the bug and expected behavior

Shaketune Vibration Calibration results are not being generated into a PNG and are not being archived either.

### Additional information and klippy.log

[klippy (3).log](https://github.com/Frix-x/klippain-shaketune/files/14627592/klippy.3.log)

It seems it happens when I modify the test parameters. I'm lowering the accel.

**Comment by Frix-x** [comment] 2024-03-18 10:52
Hi, looking at your klippy.log, this is a duplicate of #63 

I'm currently doing some work on this macro and it will be completely rewritten with a lot of new stuff and data in it. So this bug will be fixed of course, since the part of the code where it happened will no longer be used.

**Closed by Frix-x** 2024-03-18 10:52 UTC
Labels: bug
