### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by arsonists** [Frix-x/klippain-shaketune#127] opened 2024-06-18 06:20 UTC
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.0.1

### Describe the bug and expected behavior

Errors when installing as instructed:

wget -O - https://raw.githubusercontent.com/Frix-x/klippain-shaketune/main/install.sh | bash

WARNING: Ignoring invalid distribution -atplotlib (/home/pi/klippy-env/lib/pytho n3.9/site-packages)

ERROR: Could not install packages due to an OSError: [Errno 13] Permission denie d: '/home/pi/klippy-env/lib/python3.9/site-packages/mpl_toolkits/mplot3d/proj3d. py'.
Check permissions.
![Screenshot_16](https://github.com/Frix-x/klippain-shaketune/assets/22270830/cbd1f7ed-e910-4243-b545-8fbc2f17d07d)

**Comment by Frix-x** [comment] 2024-06-18 08:15
Hello, this is a duplicate of #116 

It seems there is a bug in how RatOS is creating the Klipper virtual environement and the permissions on some of the folders inside it are broken. There is a workaround in #116

I'll open an issue on RatOS repository to let them know

**Closed by Frix-x** 2024-06-18 08:15 UTC
Labels: bug, duplicate
