### ISSUE TITLE
No CSV files found in the /tmp folder to create the vibration graphs!

### ISSUE THREAD

**Issue by wiggywoosaa** [Frix-x/klippain-shaketune#56] opened 2024-01-29 14:51 UTC
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.5.0-0-g84c406b4

### Describe the bug and expected behavior

After running Vibrations Calibrations or Axes Map Calibration I received the No CSV files found in the /tmp folder to create the vibration graphs! in the cli windows. I have checked the /tmp file and the files are indeed present

**Comment by dhruvinsh** [comment] 2024-02-03 13:01
Patch
```
diff --git a/K-ShakeTune/scripts/is_workflow.py b/K-ShakeTune/scripts/is_workflow.py
index dde04f6..1ea631c 100755
--- a/K-ShakeTune/scripts/is_workflow.py
+++ b/K-ShakeTune/scripts/is_workflow.py
@@ -136,7 +136,7 @@ def create_vibrations_graph(axis_name, accel, chip_name, keep_csv):
     current_date = datetime.now().strftime('%Y%m%d_%H%M%S')
     lognames = []
-    globbed_files = glob.glob(f'/tmp/{chip_name}-*.csv')
+    globbed_files = glob.glob(f'/tmp/adxl345-{chip_name}-*.csv')
     if not globbed_files:
         print("No CSV files found in the /tmp folder to create the vibration graphs!")
         sys.exit(1)
```

**Comment by arsonists** [comment] 2024-02-09 07:01
Good morning,

I have the same problem, how can I apply the update?

**Comment by wiggywoosaa** [comment] 2024-02-09 07:36
find this file -  K-ShakeTune/scripts/is_workflow.py

remove this line - globbed_files = glob.glob(f'/tmp/{chip_name}-*.csv')
replace it with this - globbed_files = glob.glob(f'/tmp/adxl345-{chip_name}-*.csv')

**Comment by arsonists** [comment] 2024-02-09 08:37
thank you very much

**Comment by Frix-x** [comment] 2024-02-09 09:15
> Patch
> 
> ```
> diff --git a/K-ShakeTune/scripts/is_workflow.py b/K-ShakeTune/scripts/is_workflow.py
> index dde04f6..1ea631c 100755
> --- a/K-ShakeTune/scripts/is_workflow.py
> +++ b/K-ShakeTune/scripts/is_workflow.py
> @@ -136,7 +136,7 @@ def create_vibrations_graph(axis_name, accel, chip_name, keep_csv):
>      current_date = datetime.now().strftime('%Y%m%d_%H%M%S')
>      lognames = []
> -    globbed_files = glob.glob(f'/tmp/{chip_name}-*.csv')
> +    globbed_files = glob.glob(f'/tmp/adxl345-{chip_name}-*.csv')
>      if not globbed_files:
>          print("No CSV files found in the /tmp folder to create the vibration graphs!")
>          sys.exit(1)
> ```

Hello, thanks for sharing this patch. In fact it was like this before and I had to change it since it break the compatibility with LIS2DW and other kind of sensors. This issue is in fact a duplicate of #44 .

I'll work on a proper fix to be able to get it work with all kind of sensors and with configuration where they have "custom names". In the meantime, avoid using `[adxl345 my_custom_name]` for everything to work correctly :)

**Comment by Frix-x** [comment] 2024-03-04 13:23
I'll close this one in favor of #44

**Closed by Frix-x** 2024-03-04 13:23 UTC
Labels: bug, duplicate
